name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create ZIP
      run: |
        zip -r competitive-scheduling.zip . \
          -x "*.git*" \
          "node_modules/*" \
          ".husky/*" \
          ".vscode/*" \
          "*.log" \
          ".eslint*" \
          ".stylelint*" \
          ".prettier*" \
          "postcss.config.js" \
          "tailwind.config.js" \
          "package-lock.json" \
          "package.json" \
          ".gitignore" \
          "README.md" \
          "README-pt-BR.md" \
          "CHANGELOG.md" \
          "releases/*" \
          ".github/*"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: competitive-scheduling.zip